added Aave test
strips-finance/apy pull request #6
Opened 2021-11-21 14:57 UTC by alex-sumner

2021-11-22 08:55 UTC, kshilov requested changes

2021-11-22 08:55 UTC, kshilov commented on test/compoundDraft.ts
> +    const UINT256_MAX = ethers.BigNumber.from("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
Use constants please: ethers.constants.MaxUint256

details here: https://docs.ethers.io/v5/api/utils/constants/

2021-11-22 08:55 UTC, kshilov commented on test/compoundDraft.ts
> +        tx = await this.aaveLendingPool.withdraw(this.USDC.address, UINT256_MAX, this.deployer.address);
How is that possible? You withdraw more than you supplied ?

2021-11-22 08:55 UTC, kshilov commented on test/compoundDraft.ts
> +        console.log("PROFIT earned=" + profit.toString() + " passed periods=" + periods);
We also should add yield farming somewhere here. It's AAVE token or something like that.

So you supply USDC, and get back profit NOT only in USDC but also in "platform token" (AAVE) - we need to calculate this profit as well.

2021-11-22 13:08 UTC, alex-sumner commented on test/compoundDraft.ts
> +    const UINT256_MAX = ethers.BigNumber.from("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
No problem

2021-11-22 13:10 UTC, alex-sumner commented on test/compoundDraft.ts
> +        console.log("PROFIT earned=" + profit.toString() + " passed periods=" + periods);
Yes, that is to come...

2021-11-22 13:12 UTC, alex-sumner commented on test/compoundDraft.ts
> +        tx = await this.aaveLendingPool.withdraw(this.USDC.address, UINT256_MAX, this.deployer.address);
See https://docs.aave.com/developers/the-core-protocol/lendingpool#withdraw

2021-11-25 14:52 UTC, kshilov approved these changes
lgtm

2021-11-25 14:52 UTC, merged